### ISSUE TITLE
Python setup.py installation does not work

### ISSUE THREAD

**Issue by kdmarrett** [SEU-ALLEN-codebase/v3d-py-helper#1]
~/v3d-py-helper$ python3 setup.py build_ext --inplace
running build_ext
building 'v3dpy.loaders.pbd' extension
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/kdmarrett/.local/lib/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -c v3dpy/loaders/pbd.c -o build/temp.linux-x86_64-3.10/v3dpy/loaders/pbd.o
cc1: fatal error: v3dpy/loaders/pbd.c: No such file or directory
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

**Comment by zzhmark** [comment]
From the other thread.
if your Python version is too low, there might be some issues with Cython grammar, far as I know.
I haven't tested all the earlier versions than 3.10
