### ISSUE TITLE
Pip installation does not work

### ISSUE THREAD

**Issue by kdmarrett** [SEU-ALLEN-codebase/v3d-py-helper#2]
~/v3d-py-helper$ pip3 install v3d-py-helper
Defaulting to user installation because normal site-packages is not writeable
Collecting v3d-py-helper
  Using cached v3d-py-helper-0.1.0.tar.gz (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package v3d-py-helper produced metadata for project name unknown. Fix your #egg=v3d-py-helper fragments.
Discarding https://files.pythonhosted.org/packages/22/28/8bc9b4549db7b8ab403804b2beca9445857992b757a0c67a6731aeb83cd3/v3d-py-helper-0.1.0.tar.gz#sha256=2328c5a26e04a07c0ad552f96a123bee12f8dc67e4a74f27d1f3c49e39039301 (from https://pypi.org/simple/v3d-py-helper/) (requires-python:>=3.9): Requested unknown from https://files.pythonhosted.org/packages/22/28/8bc9b4549db7b8ab403804b2beca9445857992b757a0c67a6731aeb83cd3/v3d-py-helper-0.1.0.tar.gz#sha256=2328c5a26e04a07c0ad552f96a123bee12f8dc67e4a74f27d1f3c49e39039301 has inconsistent name: filename has 'v3d-py-helper', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement v3d-py-helper (from versions: 0.1.0)
ERROR: No matching distribution found for v3d-py-helper

**Comment by zzhmark** [comment]
what's your python version by the way?

**Comment by zzhmark** [comment]
You can try 3.10 to see if the err msg persists, which is the one I am developing on. 
but if you really need an older one, I can pack it for you.
